### ISSUE TITLE
Running the tests in a non-interactive environment like Github Actions

### ISSUE THREAD

**Issue by karl-run** [timokoessler/interactive-cli-tester#1]
-   Is your feature request related to a problem?

Hi! I tried out your library on a little CLI we have, here are the tests:

https://github.com/navikt/tsm-cli/blob/main/tests/tsmx.test.ts

These work fine locally, but they fail in a Github Actions job. Here is [the failed test](https://github.com/navikt/tsm-cli/actions/runs/11631424932/job/32392468434) (it doesn't say anything why it failed). My immediate thought is that interactivity does not work in a "headless" environment such as Github Actions.

-   Add any other context about the feature request.

Very cool that the library worked with bun without any issues. :smile:

**Comment by timokoessler** [comment]
Hi!
This library should work in Github Actions (the tests in this repo are using Github Actions too).
I cloned the repo and executed the tests on my device (macOS) and I get the same error locally.
The reason might be:
```
No teams found!
Please configure a team with:
tsm config --team=<team-name>
```

Nice to know that it works in Bun 😎

**Comment by karl-run** [comment]
Oh shit that's embarrassing. :facepalm: Of course, when testing locally the binary uses my existing configuration. :sweat_smile: 

Thanks!

**Comment by timokoessler** [comment]
I don't like debugging tests that only fail in CI either, and sometimes it's so obvious 😅.
